#!/bin/sh
#
# ~/bin/acp
#
# See acp(1) for usage.

. ~/.acp.conf

case "$1" in
-a)
	$RSYNC -avz --delete --exclude=$EXCLUDE -e "$SSH -p $PORT" \
		$RUSER@$RHOST:$DIR/$USER/ $DIR/$USER/
	;;
-s)
	$RSYNC -avz --delete --exclude=$EXCLUDE -e "$SSH -p $PORT" \
		$DIR/$USER/ $RUSER@$RHOST:$DIR/$USER/
	;;
-d)
	$RSYNC -avz --delete --exclude=$EXCLUDE -e "$SSH -p $PORT" \
		$RUSER@$RHOST:$DIR/ $DIR/
	;;
-f)
	$RSYNC -avz --delete --exclude=$EXCLUDE -e "$SSH -p $PORT" \
		$DIR/ $RUSER@$RHOST:$DIR/
	;;
*)
	echo "usage: `basename $0` [-a] [-s] [-d] [-f]"
	;;
esac
