.Dd $Mdocdate: June 04 2010 $
.Dt ACP 1
.Os
.Sh NAME
.Nm acp
.Nd sync $RHOST files
.Sh SYNOPSIS
.Nm acp
.Op Fl a
.Op Fl s
.Op Fl d
.Op Fl f
.Sh DESCRIPTION
The
.Nm
utility syncs files between $DIR and $RHOST.
.Bl -tag -width Ds
.It Fl a
Pull from $RHOST
.It Fl s
Push to $USER.$RHOST
.It Fl d
Pull from $RHOST (full)
.It Fl f
Push to $RHOST (full)
.El
.Sh ENVIRONMENT
.Ev USER
Name of subdomain for the
.Fl a
and 
.Fl s
options.
.Sh FILES
.Ar ~/.acp.conf
Specifies the variables in use.
.Sh EXAMPLES
After editing the docs directory, push to remote:
.Pp
.D1 $ acp \-s
.Pp
Make sure you're up to date:
.Pp
.D1 $ acp \-d
.Pp
Sync a new post:
.Pp
.D1 $ acp \-f
.Sh AUTHOR
Andrew Antle
.Sh BUGS
Ha! Surely you must be joking. <bugs at antlechrist dot org>
