#!/bin/sh

. ~/.geerc

entry() {
	for i in `ls -F *.$EXT | grep -v index.$EXT | sort -r`; do
		post=`echo $i | sed "s/.\$EXT$/.html/"`
		title=`cat $i | sed 1q`
		updated="`echo $i | cut -c -10`T00:00:00-04:00"
		cat <<END
<entry>
<title>$title</title>
<link href="/$post"/>
<updated>$updated</updated>
<id>tag:$POSTURL,$updated:/$post</id>
<content type="html">
END
		cat $i | $FMT $XMLESCOPTS | sed 1d
		cat <<END
</content>
</entry>
END
	done
}

feed() {
	updated=`date --rfc-3339=seconds | sed 's/ /T/'`
	cat <<END
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
<title>$POSTURL</title>
<link href="http://$POSTURL/atom.xml" rel="self"/>
<link href="http://$POSTURL/"/>
<updated>$updated</updated>
<id>http://$POSTURL/</id>
<author>
<name>$REALNAME</name>
</author>
END
	entry
	cat <<END
</feed>
END
}

make_site() {
	if test $1; then
		cd $1
	fi
	process "./" "<a href=\"/\">$URL/" /
}

menu() {
	for i in `ls -F $1 | grep -v index.$EXT | sort $REVERSE`; do
		case $i in
		*.$EXT)
			base=`echo $i | sed "s/.\$EXT$//"`
			cleanbase=`echo $base | sed 's/_/ /g'`
			if test "x$base" = "x$2"; then
				echo "\
<li class='current'><a href=\"$base.html\">$cleanbase</a></li>"
			else
				echo "\
<li><a href=\"$base.html\">$cleanbase</a></li>"
			fi
			cur=1
			;;
		*/)
			echo "<li><a href=\"$i\">$i</a></li>"
			;;
		esac
	done
	cat <<END
</ul>
</nav>
</header>
END
}

page() {
	mtime=`ls -l $1$2.$EXT | awk '{ print $6" at "$7 }'`
	title="$URL`echo $4 | sed 's/.html//'`"
	cat <<END
<!DOCTYPE html>
<html lang="en">
<head>
<title>$title</title>
<meta charset="utf-8" />
<meta name="viewport" content="user-scalable=no, width=device-width" />
<link href="$S/favicon.png" rel="shortcut icon" />
<link href="$S/mobile.css" rel="stylesheet"
      media="only screen and (max-width: 480px)" />
<link href="$S/style.css" rel="stylesheet"
      media="screen and (min-width: 481px)" />
<!--[if IE]>
<link href="$S/ie.css" rel="stylesheet" media="all" />
<![endif]-->
END
	if test $REVERSE; then
		cat <<END
<link href="/atom.xml" rel="alternate" type="application/atom+xml" />
END
	fi
	cat <<END
</head>
<body>
<header>
<hgroup><h1>$3</a></h1></hgroup>
<nav>
<ul>
END
	menu $1 $2
	cat <<END
<article>
END
	cat $1$2.$EXT | $FMT
	cat <<END
</article>
<footer>
<section class="l">
Powered by <a href="http://github.com/antlechrist/gee">gee</a><br />
<a href="$2.$EXT">Page source</a> |
<a href="http://antlechrist.org/">Main</a>
</section>
<section class="r">
Last modified: $mtime<br />
<a href="$S/LICENSE">© 2009-2010</a>
<a href="mailto:andrew@antlechrist.org">Andrew Antle</a>
</section>
</footer>
</body>
</html>
END
}

process() {
	for i in `ls -F $1`; do
		case $i in
		*.$EXT)
			echo "processing $1$i"
			base=`echo $i | sed "s/.\$EXT$//"`
			if test x$base = xindex; then
				title=$3
			else
				title=$3$base.html
			fi
			page "$1" "$base" "$2" "$title" > "$1$base.html"
			;;
		*/)
			process "$1$i" "$2</a><a href=\"$PREFIX`echo $1 | \
				sed 's/.\///'`$i\">$i" $3$i
			;;
		*)
			;;
		esac
	done
}

usage() {
	echo "usage: gee [-c] [-e title] [-f] [-n] [-o] [-p] [-s]" && exit 1
}

# main
if test $# -eq 0; then
	usage
fi

while getopts ":ce:fnops" OPT; do
	case $OPT in
	c)
		rm `du -a | awk '{ print $2 }' | grep \\.html$`
		;;
	e)
		$EDITOR $DIR/posts/`date '+%Y-%m-%d'`-"$OPTARG".md
		;;
	f)
		feed > atom.xml
		;;
	n)
		$RSYNC -avz --delete --exclude=$EXCLUDE -e "$SSH -p $PORT" \
			$RUSER@$RHOST:$DIR/ $DIR/
		;;
	o)
		$RSYNC -avz --delete --exclude=$EXCLUDE -e "$SSH -p $PORT" \
			$DIR/ $RUSER@$RHOST:$DIR/
		;;
	p)
		URL=$POSTURL REVERSE="-r" make_site
		;;
	s)
		URL=$FULLURL make_site 
		;;
	*)
		usage
		;;
	esac
done
shift $(($OPTIND - 1))
exit $?
